/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as TenantsQuotasIndexRouteImport } from './routes/tenants-quotas/index'
import { Route as TenantsBillingIndexRouteImport } from './routes/tenants-billing/index'
import { Route as TenantsAdminsIndexRouteImport } from './routes/tenants-admins/index'
import { Route as OverviewKbIndexRouteImport } from './routes/overview-kb/index'
import { Route as OverviewInferenceIndexRouteImport } from './routes/overview-inference/index'
import { Route as OverviewGpuIndexRouteImport } from './routes/overview-gpu/index'
import { Route as OverviewCapacityIndexRouteImport } from './routes/overview-capacity/index'
import { Route as OverviewAlertsIndexRouteImport } from './routes/overview-alerts/index'
import { Route as OpsStorageIndexRouteImport } from './routes/ops-storage/index'
import { Route as OpsPoolIndexRouteImport } from './routes/ops-pool/index'
import { Route as OpsNodesIndexRouteImport } from './routes/ops-nodes/index'
import { Route as OpsGpuIndexRouteImport } from './routes/ops-gpu/index'
import { Route as TenantsTenantIdRouteImport } from './routes/tenants/$tenantId'
import { Route as TenantsQuotasPlanCodeRouteImport } from './routes/tenants-quotas/$planCode'
import { Route as TenantsBillingTenantIdRouteImport } from './routes/tenants-billing/$tenantId'
import { Route as TenantsAdminsAdminIdRouteImport } from './routes/tenants-admins/$adminId'

const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantsRoute,
} as any)
const TenantsQuotasIndexRoute = TenantsQuotasIndexRouteImport.update({
  id: '/tenants-quotas/',
  path: '/tenants-quotas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsBillingIndexRoute = TenantsBillingIndexRouteImport.update({
  id: '/tenants-billing/',
  path: '/tenants-billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsAdminsIndexRoute = TenantsAdminsIndexRouteImport.update({
  id: '/tenants-admins/',
  path: '/tenants-admins/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewKbIndexRoute = OverviewKbIndexRouteImport.update({
  id: '/overview-kb/',
  path: '/overview-kb/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewInferenceIndexRoute = OverviewInferenceIndexRouteImport.update({
  id: '/overview-inference/',
  path: '/overview-inference/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewGpuIndexRoute = OverviewGpuIndexRouteImport.update({
  id: '/overview-gpu/',
  path: '/overview-gpu/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewCapacityIndexRoute = OverviewCapacityIndexRouteImport.update({
  id: '/overview-capacity/',
  path: '/overview-capacity/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewAlertsIndexRoute = OverviewAlertsIndexRouteImport.update({
  id: '/overview-alerts/',
  path: '/overview-alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsStorageIndexRoute = OpsStorageIndexRouteImport.update({
  id: '/ops-storage/',
  path: '/ops-storage/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsPoolIndexRoute = OpsPoolIndexRouteImport.update({
  id: '/ops-pool/',
  path: '/ops-pool/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsNodesIndexRoute = OpsNodesIndexRouteImport.update({
  id: '/ops-nodes/',
  path: '/ops-nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsGpuIndexRoute = OpsGpuIndexRouteImport.update({
  id: '/ops-gpu/',
  path: '/ops-gpu/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsTenantIdRoute = TenantsTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => TenantsRoute,
} as any)
const TenantsQuotasPlanCodeRoute = TenantsQuotasPlanCodeRouteImport.update({
  id: '/tenants-quotas/$planCode',
  path: '/tenants-quotas/$planCode',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsBillingTenantIdRoute = TenantsBillingTenantIdRouteImport.update({
  id: '/tenants-billing/$tenantId',
  path: '/tenants-billing/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsAdminsAdminIdRoute = TenantsAdminsAdminIdRouteImport.update({
  id: '/tenants-admins/$adminId',
  path: '/tenants-admins/$adminId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/tenants-admins/$adminId': typeof TenantsAdminsAdminIdRoute
  '/tenants-billing/$tenantId': typeof TenantsBillingTenantIdRoute
  '/tenants-quotas/$planCode': typeof TenantsQuotasPlanCodeRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/ops-gpu': typeof OpsGpuIndexRoute
  '/ops-nodes': typeof OpsNodesIndexRoute
  '/ops-pool': typeof OpsPoolIndexRoute
  '/ops-storage': typeof OpsStorageIndexRoute
  '/overview-alerts': typeof OverviewAlertsIndexRoute
  '/overview-capacity': typeof OverviewCapacityIndexRoute
  '/overview-gpu': typeof OverviewGpuIndexRoute
  '/overview-inference': typeof OverviewInferenceIndexRoute
  '/overview-kb': typeof OverviewKbIndexRoute
  '/tenants-admins': typeof TenantsAdminsIndexRoute
  '/tenants-billing': typeof TenantsBillingIndexRoute
  '/tenants-quotas': typeof TenantsQuotasIndexRoute
  '/tenants/': typeof TenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tenants-admins/$adminId': typeof TenantsAdminsAdminIdRoute
  '/tenants-billing/$tenantId': typeof TenantsBillingTenantIdRoute
  '/tenants-quotas/$planCode': typeof TenantsQuotasPlanCodeRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/ops-gpu': typeof OpsGpuIndexRoute
  '/ops-nodes': typeof OpsNodesIndexRoute
  '/ops-pool': typeof OpsPoolIndexRoute
  '/ops-storage': typeof OpsStorageIndexRoute
  '/overview-alerts': typeof OverviewAlertsIndexRoute
  '/overview-capacity': typeof OverviewCapacityIndexRoute
  '/overview-gpu': typeof OverviewGpuIndexRoute
  '/overview-inference': typeof OverviewInferenceIndexRoute
  '/overview-kb': typeof OverviewKbIndexRoute
  '/tenants-admins': typeof TenantsAdminsIndexRoute
  '/tenants-billing': typeof TenantsBillingIndexRoute
  '/tenants-quotas': typeof TenantsQuotasIndexRoute
  '/tenants': typeof TenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/tenants-admins/$adminId': typeof TenantsAdminsAdminIdRoute
  '/tenants-billing/$tenantId': typeof TenantsBillingTenantIdRoute
  '/tenants-quotas/$planCode': typeof TenantsQuotasPlanCodeRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/ops-gpu/': typeof OpsGpuIndexRoute
  '/ops-nodes/': typeof OpsNodesIndexRoute
  '/ops-pool/': typeof OpsPoolIndexRoute
  '/ops-storage/': typeof OpsStorageIndexRoute
  '/overview-alerts/': typeof OverviewAlertsIndexRoute
  '/overview-capacity/': typeof OverviewCapacityIndexRoute
  '/overview-gpu/': typeof OverviewGpuIndexRoute
  '/overview-inference/': typeof OverviewInferenceIndexRoute
  '/overview-kb/': typeof OverviewKbIndexRoute
  '/tenants-admins/': typeof TenantsAdminsIndexRoute
  '/tenants-billing/': typeof TenantsBillingIndexRoute
  '/tenants-quotas/': typeof TenantsQuotasIndexRoute
  '/tenants/': typeof TenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tenants'
    | '/tenants-admins/$adminId'
    | '/tenants-billing/$tenantId'
    | '/tenants-quotas/$planCode'
    | '/tenants/$tenantId'
    | '/ops-gpu'
    | '/ops-nodes'
    | '/ops-pool'
    | '/ops-storage'
    | '/overview-alerts'
    | '/overview-capacity'
    | '/overview-gpu'
    | '/overview-inference'
    | '/overview-kb'
    | '/tenants-admins'
    | '/tenants-billing'
    | '/tenants-quotas'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tenants-admins/$adminId'
    | '/tenants-billing/$tenantId'
    | '/tenants-quotas/$planCode'
    | '/tenants/$tenantId'
    | '/ops-gpu'
    | '/ops-nodes'
    | '/ops-pool'
    | '/ops-storage'
    | '/overview-alerts'
    | '/overview-capacity'
    | '/overview-gpu'
    | '/overview-inference'
    | '/overview-kb'
    | '/tenants-admins'
    | '/tenants-billing'
    | '/tenants-quotas'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/tenants'
    | '/tenants-admins/$adminId'
    | '/tenants-billing/$tenantId'
    | '/tenants-quotas/$planCode'
    | '/tenants/$tenantId'
    | '/ops-gpu/'
    | '/ops-nodes/'
    | '/ops-pool/'
    | '/ops-storage/'
    | '/overview-alerts/'
    | '/overview-capacity/'
    | '/overview-gpu/'
    | '/overview-inference/'
    | '/overview-kb/'
    | '/tenants-admins/'
    | '/tenants-billing/'
    | '/tenants-quotas/'
    | '/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantsRoute: typeof TenantsRouteWithChildren
  TenantsAdminsAdminIdRoute: typeof TenantsAdminsAdminIdRoute
  TenantsBillingTenantIdRoute: typeof TenantsBillingTenantIdRoute
  TenantsQuotasPlanCodeRoute: typeof TenantsQuotasPlanCodeRoute
  OpsGpuIndexRoute: typeof OpsGpuIndexRoute
  OpsNodesIndexRoute: typeof OpsNodesIndexRoute
  OpsPoolIndexRoute: typeof OpsPoolIndexRoute
  OpsStorageIndexRoute: typeof OpsStorageIndexRoute
  OverviewAlertsIndexRoute: typeof OverviewAlertsIndexRoute
  OverviewCapacityIndexRoute: typeof OverviewCapacityIndexRoute
  OverviewGpuIndexRoute: typeof OverviewGpuIndexRoute
  OverviewInferenceIndexRoute: typeof OverviewInferenceIndexRoute
  OverviewKbIndexRoute: typeof OverviewKbIndexRoute
  TenantsAdminsIndexRoute: typeof TenantsAdminsIndexRoute
  TenantsBillingIndexRoute: typeof TenantsBillingIndexRoute
  TenantsQuotasIndexRoute: typeof TenantsQuotasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof TenantsRoute
    }
    '/tenants-quotas/': {
      id: '/tenants-quotas/'
      path: '/tenants-quotas'
      fullPath: '/tenants-quotas'
      preLoaderRoute: typeof TenantsQuotasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-billing/': {
      id: '/tenants-billing/'
      path: '/tenants-billing'
      fullPath: '/tenants-billing'
      preLoaderRoute: typeof TenantsBillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-admins/': {
      id: '/tenants-admins/'
      path: '/tenants-admins'
      fullPath: '/tenants-admins'
      preLoaderRoute: typeof TenantsAdminsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-kb/': {
      id: '/overview-kb/'
      path: '/overview-kb'
      fullPath: '/overview-kb'
      preLoaderRoute: typeof OverviewKbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-inference/': {
      id: '/overview-inference/'
      path: '/overview-inference'
      fullPath: '/overview-inference'
      preLoaderRoute: typeof OverviewInferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-gpu/': {
      id: '/overview-gpu/'
      path: '/overview-gpu'
      fullPath: '/overview-gpu'
      preLoaderRoute: typeof OverviewGpuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-capacity/': {
      id: '/overview-capacity/'
      path: '/overview-capacity'
      fullPath: '/overview-capacity'
      preLoaderRoute: typeof OverviewCapacityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-alerts/': {
      id: '/overview-alerts/'
      path: '/overview-alerts'
      fullPath: '/overview-alerts'
      preLoaderRoute: typeof OverviewAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-storage/': {
      id: '/ops-storage/'
      path: '/ops-storage'
      fullPath: '/ops-storage'
      preLoaderRoute: typeof OpsStorageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-pool/': {
      id: '/ops-pool/'
      path: '/ops-pool'
      fullPath: '/ops-pool'
      preLoaderRoute: typeof OpsPoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-nodes/': {
      id: '/ops-nodes/'
      path: '/ops-nodes'
      fullPath: '/ops-nodes'
      preLoaderRoute: typeof OpsNodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-gpu/': {
      id: '/ops-gpu/'
      path: '/ops-gpu'
      fullPath: '/ops-gpu'
      preLoaderRoute: typeof OpsGpuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$tenantId': {
      id: '/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof TenantsTenantIdRouteImport
      parentRoute: typeof TenantsRoute
    }
    '/tenants-quotas/$planCode': {
      id: '/tenants-quotas/$planCode'
      path: '/tenants-quotas/$planCode'
      fullPath: '/tenants-quotas/$planCode'
      preLoaderRoute: typeof TenantsQuotasPlanCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-billing/$tenantId': {
      id: '/tenants-billing/$tenantId'
      path: '/tenants-billing/$tenantId'
      fullPath: '/tenants-billing/$tenantId'
      preLoaderRoute: typeof TenantsBillingTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-admins/$adminId': {
      id: '/tenants-admins/$adminId'
      path: '/tenants-admins/$adminId'
      fullPath: '/tenants-admins/$adminId'
      preLoaderRoute: typeof TenantsAdminsAdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TenantsRouteChildren {
  TenantsTenantIdRoute: typeof TenantsTenantIdRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
}

const TenantsRouteChildren: TenantsRouteChildren = {
  TenantsTenantIdRoute: TenantsTenantIdRoute,
  TenantsIndexRoute: TenantsIndexRoute,
}

const TenantsRouteWithChildren =
  TenantsRoute._addFileChildren(TenantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantsRoute: TenantsRouteWithChildren,
  TenantsAdminsAdminIdRoute: TenantsAdminsAdminIdRoute,
  TenantsBillingTenantIdRoute: TenantsBillingTenantIdRoute,
  TenantsQuotasPlanCodeRoute: TenantsQuotasPlanCodeRoute,
  OpsGpuIndexRoute: OpsGpuIndexRoute,
  OpsNodesIndexRoute: OpsNodesIndexRoute,
  OpsPoolIndexRoute: OpsPoolIndexRoute,
  OpsStorageIndexRoute: OpsStorageIndexRoute,
  OverviewAlertsIndexRoute: OverviewAlertsIndexRoute,
  OverviewCapacityIndexRoute: OverviewCapacityIndexRoute,
  OverviewGpuIndexRoute: OverviewGpuIndexRoute,
  OverviewInferenceIndexRoute: OverviewInferenceIndexRoute,
  OverviewKbIndexRoute: OverviewKbIndexRoute,
  TenantsAdminsIndexRoute: TenantsAdminsIndexRoute,
  TenantsBillingIndexRoute: TenantsBillingIndexRoute,
  TenantsQuotasIndexRoute: TenantsQuotasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
